/* Admin-only screens; the API enforces every permission and mutation. */
(()=>{'use strict';
 const $=id=>document.getElementById(id),api=NodoAPI,esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),date=s=>s?new Date(s).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'}):'확인 불가';
 const menus={overview:'운영 요약',posts:'게시글 관리',comments:'댓글 관리',analytics:'단지 이용 통계',status:'데이터·서비스 상태',audit:'운영 이력'},actions={hide:'숨김',restore:'복원',pin:'공지 고정',unpin:'공지 해제'};
 const reasonLabel=c=>({spam:'광고·도배',abuse:'욕설·비방',privacy:'개인정보 노출',other:'기타 운영 기준',board:'게시판 운영 관리'})[c]||c;
 let params=new URLSearchParams(location.search),sequence=0,rows=[],pending=null;
 const cache=new Map(),view=()=>Object.hasOwn(menus,params.get('view'))?params.get('view'):'overview',days=()=>[1,7,30].includes(Number(params.get('days')))?Number(params.get('days')):7;
 const href=(v,extra={})=>'/admin/?'+new URLSearchParams({view:v,...extra});
 function asset(path){if(!cache.has(path))cache.set(path,fetch(path).then(r=>{if(!r.ok)throw Error('자료를 불러오지 못했습니다.');return r.json();}).catch(e=>{cache.delete(path);throw e;}));return cache.get(path);}
 async function apartment(id){const c=await asset('/data/apartments/index.json'),ref=c.lookup[id];return ref?(await asset('/data/apartments/summary/'+ref[1]+'.json'))[ref[0]]:null;}
 async function context(page,id,parent){
  if(page==='community')return {label:'게시판',url:'/board/?post='+(parent||id)+'&comment='+id};if(page==='div')return {label:'배당·소각',url:'/div/?comment='+id};
  if(page?.startsWith('apt_')){try{const c=await asset('/data/apartments/index.json'),ref=c.legacy[page.slice(4)];if(ref){const a=await apartment(ref[0]);return {label:(a?.name||'아파트')+' · '+ref[1]+'㎡',url:'/apartment/?'+new URLSearchParams({id:ref[0],area:ref[1],tab:'comments',commentSource:page,comment:id})};}}catch{}return {label:'아파트 · 연결 확인 불가'};}
  if(page?.startsWith('company_')){const code=page.slice(8);let stock;try{stock=(await asset('/data/earnings_index.json')).stocks?.[code];}catch{}return {label:stock?.name||stock?.n||'기업 '+code,url:'/div/?company='+code+'&comment='+id};}return {label:'기타 페이지'};
 }
 function go(values){for(const[k,v]of Object.entries(values))v==null?params.delete(k):params.set(k,String(v));history.pushState(null,'','?'+params);render();}
 function select(name,label,options,value=params.get(name)){return `<label>${label}<select name="${name}">${options.map(([v,n])=>`<option value="${v}" ${String(value)===String(v)?'selected':''}>${n}</option>`).join('')}</select></label>`;}
 const period=()=>select('days','기간',[[1,'오늘'],[7,'최근 7일'],[30,'최근 30일']],days());
 const filters=inner=>'<form id="admin-filters" class="admin-filters">'+inner+'<button class="nodo-button">적용</button></form>';
 const table=(head,body)=>`<div class="nodo-table-wrap"><table class="nodo-table admin-table"><thead><tr>${head.map(h=>'<th>'+h+'</th>').join('')}</tr></thead><tbody>${body||'<tr><td colspan="'+head.length+'">표시할 자료가 없습니다.</td></tr>'}</tbody></table></div>`;
 function pager(count){const n=Number(params.get('offset'))||0;return `<div class="admin-pager"><span>총 ${count.toLocaleString()}건 · ${Math.floor(n/20)+1}페이지</span><button class="nodo-button" data-offset="${Math.max(0,n-20)}" ${!n?'disabled':''}>이전</button><button class="nodo-button" data-offset="${n+20}" ${n+20>=count?'disabled':''}>다음</button></div>`;}
 const error=e=>`<div class="nodo-status" role="status">${esc(e.message)} <button class="nodo-button" id="admin-retry">다시 시도</button></div>`;
 async function render(){const token=++sequence,v=view(),box=$('admin-content');$('admin-menu-select').value=v;document.querySelectorAll('#admin-nav a').forEach(a=>{if(new URL(a.href).searchParams.get('view')===v)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});box.innerHTML='<p role="status">불러오는 중…</p>';try{
  let html='<h2>'+menus[v]+'</h2>';
  if(v==='overview'){const d=await api.request('/api/admin/overview?days='+days());html+=filters(period())+'<p class="admin-small">한국 시간 기준 · 선택 기간에 작성된 글과 단지 이용 집계</p><div class="admin-metrics">'+[['새 게시글',d.counts.posts,'posts'],['새 댓글',d.counts.comments,'comments'],['숨김 게시글',d.counts.hiddenPosts,'posts'],['숨김 댓글',d.counts.hiddenComments,'comments'],['단지 조회',d.usage.views,'analytics'],['관심등록 행동',d.usage.hearts,'analytics'],['계산기 이동',d.usage.calculators,'analytics']].map(([n,x,target])=>`<a class="nodo-card" href="${href(target,{days:days(),...(n.startsWith('숨김')?{status:'moderated'}:{})})}">${n}<strong>${Number(x).toLocaleString()}</strong></a>`).join('')+'</div>';}
  if(v==='posts'||v==='comments'){
   const q=new URLSearchParams({kind:v,...(params.get('days')?{days:params.get('days')}:{}),status:params.get('status')||'all',scope:v==='posts'?'board':params.get('scope')||'all',q:params.get('q')||'',offset:params.get('offset')||'0'}),d=await api.request('/api/admin/comments?'+q);rows=d.data;
   html+=filters(`<label>내용·닉네임 검색<input name="q" maxlength="100" value="${esc(params.get('q')||'')}"></label>`+select('days','작성 기간',[['','전체 기간'],[1,'오늘'],[7,'최근 7일'],[30,'최근 30일']])+select('status','상태',[['all','전체'],['normal','공개'],['moderated','숨김'],['deleted','삭제'],['withdrawn','탈퇴']])+(v==='comments'?select('scope','영역',[['all','전체'],['apartment','아파트'],['company','기업'],['board','게시판']]):''));
   const list=await Promise.all(rows.map(async r=>{const c=await context(r.page_id,r.id,r.parent_id),eligible=!r.deleted_at&&r.author_status==='active'&&(!r.moderated_at||Date.now()-Date.parse(r.moderated_at)<30*86400000);return `<tr><td>${esc(c.label)}${c.url?`<a class="admin-source" href="${esc(c.url)}">원문 보기 ↗</a>`:''}<span class="admin-small">#${r.id}</span></td><td><div class="admin-preview">${esc(r.content)}</div>${r.moderation_reason?'<p class="admin-small">사유: '+esc(reasonLabel(r.moderation_reason.category))+' '+esc(r.moderation_reason.detail)+'</p>':''}</td><td>${esc(r.nickname||'탈퇴한 회원')}<div class="admin-small">${date(r.created_at)}</div></td><td><span class="admin-state">${r.deleted_at?'삭제':r.author_status!=='active'?'탈퇴':r.moderated_at?'숨김':'공개'}${r.pinned?' · 공지':''}</span><div class="nodo-actions">${eligible?`<button class="nodo-button" data-action="${r.moderated_at?'restore':'hide'}" data-id="${r.id}">${r.moderated_at?'복원':'숨김'}</button>${v==='posts'&&!r.moderated_at?`<button class="nodo-button" data-action="${r.pinned?'unpin':'pin'}" data-id="${r.id}">${r.pinned?'공지 해제':'공지 고정'}</button>`:''}`:''}</div></td></tr>`;}));html+=table(['위치','내용','작성자·시각','상태·처리'],list.join(''))+pager(d.count);
  }
  if(v==='analytics'){const d=await api.request('/api/admin/apartment-analytics?days='+days());html+=filters(period())+'<p class="admin-small">한국 시간 기준 · 방문 세션은 실제 사람 수가 아닙니다. 단지별 세션은 서로 합산하지 않습니다.</p><p>'+d.sources.map(s=>esc(({search:'검색',map:'지도',favorites:'관심단지',ranking:'랭킹',internal:'내부',direct:'직접·외부'})[s.source]||s.source)+': '+s.views+'회').join(' · ')+'</p>';const list=await Promise.all(d.data.map(async r=>{const a=await apartment(r.apartment_id);return `<tr><td><a href="/apartment/?id=${encodeURIComponent(r.apartment_id)}">${esc(a?.name||'단지 연결 확인 불가')}</a></td>${['views','sessions','hearts','trades','calculators'].map(k=>'<td>'+r[k]+'</td>').join('')}</tr>`;}));html+=table(['단지','조회','방문 세션','관심등록','실거래 탭','계산기 이동'],list.join(''));}
  if(v==='status'){const d=await api.request('/api/admin/status');html+=`<div class="nodo-card"><p>서비스 응답: 정상 · ${d.maintenance?'점검 모드':'운영 중'}</p><p>확인 시각: ${date(d.checkedAt)}</p><p class="admin-source">현재 배포 버전: ${esc(d.gitSha)}</p><p>배포 시각: ${date(d.deployedAt)}</p></div><p class="admin-small">기준일은 자료가 제공하는 값입니다. 별도 근거가 없는 항목은 확인 불가로 표시합니다.</p>`+table(['자료','상태','자료 기준일','건수·연결','출처'],d.data.map(x=>`<tr><td>${esc(x.name)}</td><td>${x.status==='ok'?'조회 정상':'불러오기 실패'}</td><td>${esc(x.updated||'확인 불가')}</td><td>${x.count!=null?Number(x.count).toLocaleString()+' '+esc(x.unit||'건'):'확인 불가'}${x.linked!=null?'<br>연결 '+Number(x.linked).toLocaleString()+'건':''}</td><td><a class="admin-source" href="${esc(x.path)}" target="_blank" rel="noopener">자료 출처</a></td></tr>`).join(''))+'<button id="admin-retry" class="nodo-button">상태 다시 확인</button>';}
  if(v==='audit'){const q=new URLSearchParams({action:params.get('action')||'',target:params.get('target')||'',offset:params.get('offset')||'0'}),d=await api.request('/api/admin/audit?'+q);html+=filters(select('action','처리 종류',[['','전체'],...Object.entries(actions)])+`<label>대상 번호<input name="target" inputmode="numeric" pattern="[0-9]*" value="${esc(params.get('target')||'')}"></label>`)+ '<p class="admin-small">최근 90일 · 도입 이후 작업만 표시합니다. 본문·이메일·IP는 기록하지 않습니다.</p>';const list=await Promise.all(d.data.map(async r=>{const c=await context(r.page_id,r.target_id),before=JSON.parse(r.before_state),after=JSON.parse(r.after_state),reason=r.reason?JSON.parse(r.reason):null;return `<tr><td>${date(r.created_at)}</td><td>${esc(r.nickname||(r.actor_id?'운영자':'삭제된 운영자'))}</td><td>${esc(c.label)} #${r.target_id}</td><td>${actions[r.action]}<p class="admin-small">${before.hidden?'숨김':'공개'} / ${before.pinned?'공지':'일반'} → ${after.hidden?'숨김':'공개'} / ${after.pinned?'공지':'일반'}</p></td><td>${reason?esc(reasonLabel(reason.category)+' '+reason.detail):'—'}</td></tr>`;}));html+=table(['시각','작업자','대상','처리','사유'],list.join(''))+pager(d.count);}
  if(token!==sequence)return;box.innerHTML=html;if($('admin-filters'))$('admin-filters').onsubmit=e=>{e.preventDefault();go({...Object.fromEntries(new FormData(e.currentTarget)),offset:0});};document.querySelectorAll('[data-offset]').forEach(b=>b.onclick=()=>go({offset:b.dataset.offset}));document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>confirmAction(rows.find(r=>String(r.id)===b.dataset.id),b.dataset.action));if($('admin-retry'))$('admin-retry').onclick=render;
 }catch(e){if(token!==sequence)return;box.innerHTML=error(e);$('admin-retry').onclick=render;}}
 function confirmAction(row,action){pending={row,action,key:crypto.randomUUID()};$('admin-action-title').textContent=actions[action]+' 확인';$('admin-action-target').textContent='#'+row.id+' · '+row.content.slice(0,100);$('admin-reason').hidden=action!=='hide';$('admin-detail').value='';$('admin-action-error').textContent='';$('admin-confirm').showModal();}
 $('admin-cancel').onclick=()=>$('admin-confirm').close();$('admin-action-form').onsubmit=async e=>{e.preventDefault();if(!pending)return;const {row,action,key}=pending,pin=action==='pin'||action==='unpin',b={expectedRevision:row.revision,...(pin?{pinned:action==='pin'}:{hidden:action==='hide',category:$('admin-category').value,detail:$('admin-detail').value})};$('admin-submit').disabled=true;try{await api.request(pin?'/api/board/posts/'+row.id+'/pin':'/api/admin/comments/'+row.id+'/moderation',{method:'PUT',headers:{'Idempotency-Key':key},body:JSON.stringify(b)});pending=null;$('admin-confirm').close();render();}catch(e){$('admin-action-error').textContent=e.message;if(e.status===409){$('admin-confirm').close();render();window.NodoUI?.toast(e.message);}}finally{$('admin-submit').disabled=false;}};
 window.addEventListener('popstate',()=>{params=new URLSearchParams(location.search);render();});
 async function start(){try{const s=await api.getState();if(!s.session){$('admin-gate').innerHTML='<p>운영자 계정으로 로그인해 주세요.</p><button id="admin-login" class="nodo-button">로그인</button>';$('admin-login').onclick=()=>api.login();return;}if(!s.isAdmin){$('admin-gate').textContent='운영자 권한이 필요합니다.';return;}$('admin-gate').hidden=true;$('admin-workspace').hidden=false;$('admin-nav').innerHTML=Object.entries(menus).map(([v,n])=>`<a href="${href(v)}">${n}</a>`).join('');$('admin-menu-select').innerHTML=Object.entries(menus).map(([v,n])=>`<option value="${v}">${n}</option>`).join('');$('admin-menu-select').onchange=e=>{params=new URLSearchParams({view:e.target.value});go({});};document.querySelectorAll('#admin-nav a').forEach(a=>a.onclick=e=>{if(e.ctrlKey||e.metaKey)return;e.preventDefault();params=new URLSearchParams(new URL(a.href).search);go({});});render();}catch(e){$('admin-gate').innerHTML=error(e);$('admin-retry').onclick=start;}}
 api.onChange(()=>{sequence++;$('admin-content').replaceChildren();$('admin-workspace').hidden=true;$('admin-gate').hidden=false;start();});start();
})();
