/* A single detail controller: isolated tab loading, stable identity, verified data. */
(() => {
  'use strict';
  const $=id=>document.getElementById(id),esc=s=>NodoUI.escape(s);
  const tabs={overview:'개요',trades:'실거래',investment:'투자분석',facts:'단지정보',location:'위치',comments:'의견'};
  const money=value=>{if(value==null)return '자료 없음';const n=Math.round(value),eok=Math.floor(n/10000),man=n%10000;return [eok?eok.toLocaleString()+'억':'',man?man.toLocaleString()+'만':''].filter(Boolean).join(' ')+(n===0?'0':'')+'원';};
  const number=n=>n==null?'미확인':Number(n).toLocaleString('ko-KR',{maximumFractionDigits:2});
  const pct=n=>n==null?'자료 없음':(n>0?'+':'')+number(n)+'%';
  const date=n=>String(n||'').replace(/^(\d{4})(\d{2})(\d{2})$/,'$1-$2-$3');
  const month=n=>String(n).replace(/^(\d{4})(\d{2})$/,'$1.$2');
  const facts=entries=>'<dl class="nodo-facts">'+entries.map(([k,v])=>`<div><dt>${esc(k)}</dt><dd>${esc(v)}</dd></div>`).join('')+'</dl>';
  const status=message=>`<div class="nodo-status">${esc(message)}</div>`;
  let catalog,apartment,area,tab='overview',client,generation=0,chart,map,commentsLoaded=false,commentsReady=false;
  const assets=new Map();
  function script(src){if(!assets.has(src))assets.set(src,new Promise((resolve,reject)=>{const el=document.createElement('script');el.src=src;el.onload=resolve;el.onerror=()=>{assets.delete(src);el.remove();reject(Error('화면 도구를 불러오지 못했습니다.'));};document.head.append(el);}));return assets.get(src);}
  function save(push=false){const p=new URLSearchParams({id:apartment.id,tab});if(area)p.set('area',area.area);history[push?'pushState':'replaceState']({apartment:true},'',location.pathname+'?'+p);}
  function selection(){const p=new URLSearchParams(location.search);tab=Object.hasOwn(tabs,p.get('tab'))?p.get('tab'):'overview';area=apartment.areas.find(a=>String(a.area)===p.get('area'))||[...apartment.areas].filter(a=>a.latest).sort((a,b)=>b.latest.date-a.latest.date||a.area-b.area)[0]||apartment.areas[0];}
  function header(){
    $('apartment-content').hidden=false;$('apartment-status').hidden=true;
    document.title=apartment.name+' 실거래·단지정보 | 노도스트림';let canonical=document.querySelector('link[rel=canonical]');if(!canonical){canonical=document.createElement('link');canonical.rel='canonical';document.head.append(canonical);}canonical.href='https://nodostream.com/apartment/?id='+encodeURIComponent(apartment.id);
    $('apartment-name').textContent=apartment.name;$('apartment-region').textContent=(apartment.region||'')+' · 아파트';$('apartment-address').textContent=apartment.address;
    $('apartment-facts').innerHTML=[`단지 전체 ${number(apartment.units)}세대`,apartment.years.length?apartment.years.join('–')+'년 준공':'준공연도 미확인',apartment.rental?'임대 단지':null].filter(Boolean).map(v=>`<span class="nodo-tag">${esc(v)}</span>`).join('');
    $('area-select').replaceChildren(...apartment.areas.map(a=>new Option(`${a.area}㎡ · ${(a.area/3.3058).toFixed(1)}평`,a.area)));
    if(area)$('area-select').value=area.area;else{$('area-select').add(new Option('평형 자료 없음',''));$('area-select').disabled=true;}
    $('area-units').textContent=area?`선택 평형 ${number(area.units)}세대`:'';
    const notices=[];if(apartment.rental)notices.push('임대 단지로 확인되어 매매 실거래 통계를 제공하지 않습니다.');if(apartment.conflict)notices.push('단지 연결 정보를 확인 중입니다. 확정되지 않은 거래는 합쳐 표시하지 않습니다.');if(['demolished','closed','partial_closed','inactive'].includes(apartment.status))notices.push('과거 또는 일부 폐쇄 이력이 있는 단지입니다. 아래 가격은 과거 거래를 포함합니다.');
    $('apartment-notices').innerHTML=notices.map(t=>`<div class="nodo-notice">${esc(t)}</div>`).join('');
    $('apartment-stamp').textContent=`거래 자료 기준 ${apartment.updated} · 국토교통부 실거래가 · 단지정보: 건축물대장·승인된 K-APT 연결`;
  }
  const metric=(label,value,hint='')=>`<div class="nodo-metric"><span>${esc(label)}</span><strong>${esc(value)}</strong><small>${esc(hint)}</small></div>`;
  const latestHint=()=>area?.latest?`${date(area.latest.date)} · ${area.latest.floor??'미확인'}층${area.latest.flags&1?' · 직거래':''}`:'해제되지 않은 거래가 없습니다.';
  async function draw(token){await script('https://cdn.jsdelivr.net/npm/chart.js@4.4.1/dist/chart.umd.min.js');if(token!==generation)return;
    const values=area?.monthly||{},keys=Object.keys(values).sort();if(!keys.length){$('price-chart-wrap').innerHTML=status('가격 추이 자료가 없습니다.');return;}
    const first=Number(keys[0].slice(0,4))*12+Number(keys[0].slice(4))-1,last=Number(keys.at(-1).slice(0,4))*12+Number(keys.at(-1).slice(4))-1;
    const labels=Array.from({length:last-first+1},(_,i)=>`${Math.floor((first+i)/12)}${String((first+i)%12+1).padStart(2,'0')}`);
    const style=getComputedStyle(document.documentElement);chart=new Chart($('price-chart'),{type:'line',data:{labels:labels.map(month),datasets:[{label:'월평균 실거래가',data:labels.map(m=>values[m]?.average/10000||null),borderColor:style.getPropertyValue('--accent').trim(),borderWidth:2,pointRadius:labels.length>100?0:2,spanGaps:false,tension:.15}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false},tooltip:{callbacks:{label:c=>money(c.parsed.y*10000)}}},scales:{x:{ticks:{color:style.getPropertyValue('--muted'),maxTicksLimit:7,maxRotation:0},grid:{display:false}},y:{ticks:{color:style.getPropertyValue('--muted'),callback:v=>v+'억'},grid:{color:style.getPropertyValue('--border')}}}}});
  }
  function txRows(rows){return rows.map(t=>`<tr class="${t.flags&6?'cancelled':''}"><td>${date(t.date)}${t.flags&2?'<small>해제 '+esc(t.cancelled)+'</small>':t.flags&4?'<small>원천에서 사라짐</small>':''}</td><td class="numeric">${esc(money(t.price))}${t.flags&1?'<small>직거래</small>':''}</td><td>${esc(t.floor??'미확인')}층</td><td>${esc(t.name)}</td></tr>`).join('');}
  async function trades(token){
    if(apartment.rental||!area)return status('매매 실거래 자료가 없습니다.');
    const inputs=await Promise.all([...new Set(area.rows.map(r=>r.district))].map(async g=>[g,await client(`data/tx/${g}.json`)]));if(token!==generation)return;
    const data=Object.fromEntries(inputs),rows=area.rows.flatMap(r=>NodoMapModel.trades(data[r.district].entries?.[String(r.i)]||{}).map(t=>({...t,name:r.name,row:r.i}))).sort((a,b)=>b.date-a.date||a.row-b.row||a.order-b.order);
    $('apartment-panel').innerHTML=`<div class="nodo-card"><div class="nodo-actions" style="justify-content:space-between;margin-bottom:18px"><h2 style="margin:0">${esc(area.area)}㎡ 실거래</h2><label class="nodo-field">기간<select id="trade-year"><option value="">전체 기간</option>${[...new Set(rows.map(t=>Math.floor(t.date/10000)))].map(y=>`<option>${y}</option>`).join('')}</select></label></div><p class="nodo-muted">해제·원천에서 사라진 거래는 표시하되 가격 통계에서 제외합니다.</p><div class="nodo-table-wrap"><table class="nodo-table"><thead><tr><th>거래일</th><th class="numeric">거래금액</th><th>층</th><th>거래기록 단지명</th></tr></thead><tbody id="trade-rows"></tbody></table></div><button id="trade-more" class="nodo-button" style="margin-top:16px">이전 거래 더 보기</button><div id="trade-count" class="nodo-muted"></div></div>`;
    let count=30;const render=()=>{const filtered=rows.filter(r=>!$('trade-year').value||String(r.date).startsWith($('trade-year').value));$('trade-rows').innerHTML=txRows(filtered.slice(0,count))||'<tr><td colspan="4">선택한 기간에 거래가 없습니다.</td></tr>';$('trade-more').hidden=count>=filtered.length;$('trade-count').textContent=`${Math.min(count,filtered.length)} / ${filtered.length}건`;};$('trade-more').onclick=()=>{count+=30;render();};$('trade-year').onchange=()=>{count=30;render();};render();
  }
  async function render(){const token=++generation;if(chart){chart.destroy();chart=null;}if(map){map.remove();map=null;}
    $('apartment-tabs').innerHTML=Object.entries(tabs).map(([id,n])=>`<button id="tab-${id}" role="tab" aria-controls="apartment-panel" aria-selected="${id===tab}" tabindex="${id===tab?0:-1}" data-tab="${id}">${n}</button>`).join('');
    $('apartment-panel').setAttribute('aria-labelledby','tab-'+tab);$('apartment-panel').innerHTML=status('자료를 불러오고 있습니다…');
    try{
      if(tab==='overview'){
        const a=area,empty=apartment.rental||!a;
        $('apartment-panel').innerHTML=empty?status(apartment.rental?'임대 단지의 매매 통계는 제공하지 않습니다. 단지정보 탭에서 기본 정보를 확인하세요.':'연결된 평형·거래 자료가 없습니다. 단지정보 탭을 확인하세요.'):`<div class="nodo-metrics">${metric('최신 유효 실거래',money(a.latest?.price),latestHint())}${metric('최근 평균가',money(a.recent?.value),a.recent?`${month(a.recent.from)}–${month(a.recent.to)} · ${a.recent.count}건`:'거래 자료 없음')}${metric('선택 평형 거래',number(a.total)+'건','해제·원천에서 사라진 거래 제외')}</div><div class="nodo-grid"><div class="nodo-card"><h2>가격 추이</h2><p class="nodo-muted">월평균 실거래가 · 거래 없는 달은 공백으로 표시</p><div id="price-chart-wrap" class="nodo-chart"><canvas id="price-chart" aria-label="월별 평균 실거래가 차트" role="img"></canvas></div></div><div class="nodo-card"><h2>단지 한눈에</h2>${facts([['단지 전체 세대수',number(apartment.units)+'세대'],['선택 평형 세대수',number(a.units)+'세대'],['주차',number(apartment.parking)+'대'],['준공연도',apartment.years.join('–')||'미확인']])}</div></div><p class="nodo-muted" style="margin:16px 0">최근 평균가는 최신 거래 연도 안에서 최근 월부터 3건 이상을 모아 계산합니다. 3건 미만이면 해당 연도 전체 거래를 사용합니다.</p><div class="nodo-card"><h2>연도별 가격</h2><div class="nodo-table-wrap"><table class="nodo-table"><thead><tr><th>연도</th><th>평균</th><th>최저</th><th>최고</th><th>건수</th></tr></thead><tbody>${Object.entries(a.yearly).reverse().map(([y,v])=>`<tr><td>${y}</td><td>${money(v.average)}</td><td>${money(v.min)}</td><td>${money(v.max)}</td><td>${v.count}</td></tr>`).join('')}</tbody></table></div></div>`;
        if(!empty)await draw(token);
      }else if(tab==='trades'){if(apartment.rental||!area)$('apartment-panel').innerHTML=status('연결된 매매 거래가 없습니다.');else await trades(token);}
      else if(tab==='investment'){
        $('apartment-panel').innerHTML=!area||apartment.rental?status('투자지표를 계산할 거래 자료가 없습니다.'):`<div class="nodo-stack">${area.rows.map(r=>`<div class="nodo-card"><h2>${esc(r.name)} · ${area.area}㎡</h2><div class="nodo-metrics">${metric('연평균성장률 · CAGR',pct(r.metrics.cagr))}${metric('최대낙폭 · MDD',pct(r.metrics.mdd))}${metric('샤프비율',number(r.metrics.sharpe))}${metric('최근 연도 모멘텀',pct(r.metrics.momentum))}${metric(r.metrics.landKind==='registry'?'등기 대지권':'추정 대지지분',number(r.metrics.land)+'㎡',r.metrics.landVerified?number(r.metrics.landVerified)+'세대 확인':'')}${metric('용적률',number(r.metrics.far)+'%')}</div></div>`).join('')}<div class="nodo-notice">기존 스크리너의 원천 단지·평형별 지표입니다. 여러 거래기록이 연결된 경우 각각 표시합니다. CAGR은 거래가 있는 첫해부터 ${Number(apartment.updated.slice(0,4))-1}년까지 연평균성장률, MDD는 연평균가 기준 최대낙폭, 샤프비율은 변동성 대비 수익률입니다.</div></div>`;

        if(area&&!apartment.rental){
          const years=Object.keys(area.yearly).sort(),box=document.createElement('div');box.className='nodo-card';box.style.marginBottom='20px';
          box.innerHTML='<h2>기간 수익률</h2><div class="nodo-actions"><label class="nodo-field">시작 연도<select id="return-start">'+years.map(y=>'<option>'+y+'</option>').join('')+'</select></label><label class="nodo-field">종료 연도<select id="return-end">'+years.map(y=>'<option>'+y+'</option>').join('')+'</select></label><strong id="period-return" style="font-size:24px"></strong></div><p class="nodo-muted">선택한 두 연도의 평균 실거래가를 비교합니다. 세금·비용은 포함하지 않으며 현재 연도는 자료 기준일까지 집계합니다.</p>';
          $('apartment-panel').prepend(box);$('return-end').value=years.at(-1)||'';
          const update=()=>{const a=$('return-start').value,b=$('return-end').value;$('period-return').textContent=a&&b&&a<=b?pct((area.yearly[b].average/area.yearly[a].average-1)*100):'기간을 확인하세요';};$('return-start').onchange=update;$('return-end').onchange=update;update();
        }
      }else if(tab==='facts'){
        $('apartment-panel').innerHTML=`<div class="nodo-card"><h2>단지 기본정보</h2>${facts([['단지명',apartment.name],['지번 주소',apartment.address],['도로명',apartment.road||'미확인'],['단지 전체 세대수',number(apartment.units)+'세대'],['선택 평형 세대수',number(area?.units)+'세대'],['준공연도',apartment.years.join('–')||'미확인'],['주차대수',number(apartment.parking)+'대'],['세대당 주차',apartment.units&&apartment.parking?number(apartment.parking/apartment.units)+'대':'미확인'],['용적률',number(apartment.far)+'%'],['확인된 필지',apartment.pnus.length+'개']])}${apartment.registry.length?'<h2 style="margin-top:24px">건축물 정보</h2>'+facts(apartment.registry.map(r=>[r.name,[r.purpose,r.units?number(r.units)+'세대':''].filter(Boolean).join(' · ')])):''}<p class="nodo-muted" style="margin-top:18px">단지·세대 정보는 건축물대장 및 승인된 K-APT 연결 자료입니다. 확인되지 않은 값은 임의로 합산하지 않습니다.</p></div>`;
      }else if(tab==='location'){
        $('apartment-panel').innerHTML=apartment.coord?'<div class="nodo-card"><h2>단지 위치</h2><div id="apartment-map" style="height:440px;border-radius:10px;z-index:0"></div><p id="parcel-status" class="nodo-muted" role="status">필지 경계를 불러오는 중…</p></div>':status('확인된 좌표가 없습니다. 주소와 단지정보는 다른 탭에서 확인할 수 있습니다.');
        if(apartment.coord){const link=document.createElement('a');link.className='nodo-button';link.textContent='주변 단지 지도에서 보기';link.href='/map/#'+new URLSearchParams({lat:apartment.coord[0],lng:apartment.coord[1],z:16});$('apartment-panel').firstElementChild.append(link);if(!document.getElementById('leaflet-css')){const l=document.createElement('link');l.id='leaflet-css';l.rel='stylesheet';l.href='https://cdn.jsdelivr.net/npm/leaflet@1.9.4/dist/leaflet.css';document.head.append(l);}await script('https://cdn.jsdelivr.net/npm/leaflet@1.9.4/dist/leaflet.js');await script('/js/map-services.js');if(token!==generation)return;map=L.map('apartment-map').setView(apartment.coord,16);L.tileLayer(NodoMapServices.tileURL,{maxZoom:19,attribution:'© V-World'}).on('tileerror',()=>{if(token===generation)$('parcel-status').textContent='배경 지도를 불러오지 못했습니다. 주소 정보는 단지정보 탭에서 확인하세요.';}).addTo(map);L.marker(apartment.coord).addTo(map).bindPopup(document.createTextNode(apartment.name));let shown=0;for(let start=0;start<apartment.pnus.length;start+=4){await Promise.allSettled(apartment.pnus.slice(start,start+4).map(async pnu=>{const fc=await NodoMapServices.parcel(pnu);if(token===generation){L.geoJSON(fc,{style:{color:'#168d79',weight:2,fillOpacity:.12}}).addTo(map);shown++;}}));if(token!==generation)return;}$('parcel-status').textContent=`확인된 필지 ${shown}/${apartment.pnus.length}개 표시 · ${apartment.parcelScope?.startsWith('representative')?'대표 필지 기준':'공개된 필지 기준'}`;}
      }else if(tab==='comments'){
        if(!area){$('apartment-panel').innerHTML=status('연결된 평형이 없어 기존 단지 의견이 없습니다. 공용 게시판에서 의견을 남겨 주세요.');return;}
        $('apartment-panel').innerHTML=`<div class="nodo-card"><h2>단지 의견</h2><label class="nodo-field">기존 의견의 단지·평형<select id="comment-source">${area.rows.map(r=>`<option value="${r.commentId}">${esc(r.name)} · ${area.area}㎡</option>`).join('')}</select></label><div id="apt-comments"></div></div>`;
        if(!commentsLoaded){await script('/js/comments.js');commentsLoaded=true;}if(token!==generation)return;if(commentsReady)await changeContainer('#apt-comments',$('comment-source').value);else{await initComments($('comment-source').value,'#apt-comments');commentsReady=true;}if(token!==generation)return;$('comment-source').onchange=()=>changePageId($('comment-source').value);
      }
    }catch(e){if(token!==generation)return;const el=$('apartment-panel');el.innerHTML=status(e.message)+'<button class="nodo-button" id="retry-tab">다시 시도</button>';$('retry-tab').onclick=render;}
  }
  $('area-select').onchange=()=>{area=apartment.areas.find(a=>String(a.area)===$('area-select').value);header();save();render();};
  $('apartment-tabs').onclick=e=>{const button=e.target.closest('[data-tab]');if(button){tab=button.dataset.tab;save();render();$('tab-'+tab).focus();}};
  $('apartment-tabs').onkeydown=e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const ids=Object.keys(tabs),i=ids.indexOf(tab);tab=ids[e.key==='Home'?0:e.key==='End'?ids.length-1:(i+(e.key==='ArrowRight'?1:-1)+ids.length)%ids.length];save();render();$('tab-'+tab).focus();};
  window.addEventListener('popstate',()=>{if(apartment){selection();header();render();}});
  window.addEventListener('nodo:theme',()=>{if(chart){const token=generation;chart.destroy();chart=null;draw(token).catch(()=>{});}});
  $('share-detail').onclick=async()=>{try{await navigator.clipboard.writeText(location.href);NodoUI.toast('상세 페이지 주소를 복사했습니다.');}catch{NodoUI.toast('주소 표시줄에서 현재 주소를 복사해 주세요.');}};
  try{const from=sessionStorage.getItem('nodoApartmentReturn');if(from&&from.startsWith('/')&&!from.startsWith('//')&&!from.startsWith('/apartment'))$('return-link').href=from;}catch{}
  $('return-link').onclick=e=>{if(history.length>1&&document.referrer&&new URL(document.referrer).origin===location.origin){e.preventDefault();history.back();}};
  async function start(){try{const response=await fetch('/data/apartments/index.json');if(!response.ok)throw Error('단지 자료를 불러오지 못했습니다.');catalog=await response.json();const p=new URLSearchParams(location.search),old=catalog.legacy[p.get('row')];const id=p.get('id')||old?.[0];const ref=catalog.lookup[id];if(!ref)throw Error('해당 단지를 찾을 수 없습니다. 단지 검색에서 다시 선택해 주세요.');client=createVerifiedDataClient('/',{...catalog.sources,...catalog.shards});const shard=await client('data/apartments/'+ref[1]+'.json');apartment=shard[ref[0]];if(old&&!p.has('area')){p.set('area',old[1]);history.replaceState(null,'','?'+p);}selection();save();header();render();}catch(e){$('apartment-status').innerHTML=esc(e.message)+' <button class="nodo-button" id="retry-detail">다시 시도</button> <a href="/">단지 검색</a>';$('retry-detail').onclick=start;}}
  start();
})();
