(() => {
  'use strict';
  const $=id=>document.getElementById(id),esc=s=>NodoUI.escape(s),api=NodoAPI;
  let auth=null,offset=0,query='',hidden=false,post=null,generation=0;
  const date=value=>new Date(value).toLocaleString('ko-KR',{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'});
  const message=error=>{$('board-status').textContent=error?.message||'';};
  const action=fn=>async e=>{const b=e.currentTarget;b.disabled=true;try{message();await fn(e);}catch(error){message(error);}finally{b.disabled=false;}};
  function navigate(id){const p=new URLSearchParams();if(id)p.set('post',id);else{if(query)p.set('q',query);if(offset)p.set('offset',offset);if(hidden)p.set('hidden','1');}history.pushState(null,'',location.pathname+(p.size?'?'+p:''));render();}
  async function list(token){
    document.title='게시판 | 노도스트림';
    const result=await api.request('/api/board/posts?'+new URLSearchParams({q:query,offset,hidden:hidden?'1':'0'}));if(token!==generation)return;
    $('board-content').innerHTML=`<div class="nodo-card"><form id="board-search" class="nodo-actions" style="margin-bottom:20px"><label class="nodo-field" style="flex:1">제목·내용 검색<input id="board-query" maxlength="100" value="${esc(query)}" placeholder="검색어를 입력하세요"></label><button class="nodo-button" style="align-self:end">검색</button>${auth?.isAdmin?`<button type="button" id="board-hidden" class="nodo-button" style="align-self:end">${hidden?'공개 글 보기':'숨긴 글 관리'}</button>`:''}</form><div class="nodo-table-wrap"><table class="nodo-table nodo-board-list"><thead><tr><th>제목</th><th>작성자</th><th>작성일</th></tr></thead><tbody>${result.data.map(p=>`<tr><td style="white-space:normal;min-width:200px">${p.pinned?'<span class="nodo-tag accent">공지</span> ':''}<a href="?post=${p.id}">${esc(p.title)}</a> <span class="nodo-muted">${p.reply_count?`[${p.reply_count}]`:''}</span>${hidden?` <button class="nodo-button" data-restore="${p.id}">숨김 해제</button>`:''}</td><td>${esc(p.nickname||'회원')}</td><td>${date(p.created_at)}</td></tr>`).join('')||'<tr><td colspan="3">'+(query?'검색 결과가 없습니다.':'아직 게시글이 없습니다. 첫 의견을 남겨 주세요.')+'</td></tr>'}</tbody></table></div><div class="nodo-actions" style="justify-content:space-between;margin-top:18px"><span class="nodo-muted">${result.count}개 글</span><div class="nodo-actions"><button id="board-prev" class="nodo-button" ${offset===0?'disabled':''}>이전</button><span>${Math.floor(offset/20)+1} / ${Math.max(1,Math.ceil(result.count/20))}</span><button id="board-next" class="nodo-button" ${offset+20>=result.count?'disabled':''}>다음</button></div></div></div>`;
    $('board-search').onsubmit=e=>{e.preventDefault();query=$('board-query').value.trim();offset=0;navigate();};$('board-prev').onclick=()=>{offset=Math.max(0,offset-20);navigate();};$('board-next').onclick=()=>{offset+=20;navigate();};if($('board-hidden'))$('board-hidden').onclick=()=>{hidden=!hidden;offset=0;navigate();};
    document.querySelectorAll('[data-restore]').forEach(b=>b.onclick=action(async()=>{await api.request('/api/admin/comments/'+b.dataset.restore+'/moderation',{method:'PUT',body:JSON.stringify({hidden:false})});render();}));
  }
  function editor(existing=null){
    if(!auth?.session){api.login();return;}if(!auth.profile?.nickname){location.href='/account/';return;}
    generation++;message();const lines=(existing?.content||'').split('\n'),title=existing?lines.shift():'';
    $('board-content').innerHTML=`<form class="nodo-card nodo-stack" id="post-editor"><h2>${existing?'글 수정':'새 글 작성'}</h2><label class="nodo-field">제목<input id="post-title" required minlength="2" maxlength="120" value="${esc(title)}" placeholder="어떤 이야기를 나누고 싶으신가요?"></label><label class="nodo-field">내용<textarea id="post-body" rows="12" required maxlength="997" placeholder="질문이나 의견을 작성해 주세요.">${esc(existing?lines.join('\n'):'')}</textarea></label><p class="nodo-muted" id="post-count">제목과 내용을 합쳐 최대 1,000자</p><div class="nodo-actions"><button class="nodo-button primary" id="post-submit">${existing?'수정 저장':'등록'}</button><button type="button" class="nodo-button" id="post-cancel">취소</button></div></form>`;
    $('post-cancel').onclick=render;const count=()=>{$('post-count').textContent=`${$('post-title').value.trim().length+1+$('post-body').value.trim().length} / 1,000자`;};$('post-title').oninput=count;$('post-body').oninput=count;
    $('post-editor').onsubmit=async e=>{e.preventDefault();const content=$('post-title').value.trim()+'\n'+$('post-body').value.trim();if(content.length>1000){message(Error('제목과 내용을 합쳐 1,000자 이하로 입력해 주세요.'));return;}$('post-submit').disabled=true;try{const result=existing?await api.request('/api/comments/'+existing.id,{method:'PATCH',body:JSON.stringify({content})}):await api.create('/api/comments',{page_id:'community',content});navigate(result.data.id);}catch(error){message(error);$('post-submit').disabled=false;}};
  }
  async function detail(id,token){
    const result=await api.request('/api/board/posts/'+id);if(token!==generation)return;post=result.data;
    const parts=post.content.split('\n'),title=parts.shift(),owner=auth?.session?.user.id===post.user_id;
    document.title=title+' | 노도스트림 게시판';
    $('board-content').innerHTML=`<article class="nodo-card"><a class="nodo-button" href="/board/">← 글 목록</a><div style="margin:22px 0">${post.pinned?'<span class="nodo-tag accent">공지</span>':''}<h2 style="font-size:26px;overflow-wrap:anywhere">${esc(title)}</h2><p class="nodo-muted">${esc(post.profiles.nickname)} · ${date(post.created_at)}${post.updated_at?' · 수정됨':''}</p></div><div style="white-space:pre-wrap;overflow-wrap:anywhere;min-height:140px;font-size:16px">${esc(parts.join('\n'))}</div><div class="nodo-actions" style="margin-top:24px">${owner&&!post.is_deleted?'<button id="post-edit" class="nodo-button">수정</button><button id="post-delete" class="nodo-button">삭제</button>':''}${auth?.isAdmin&&!post.is_deleted?`<button id="post-pin" class="nodo-button">${post.pinned?'공지 해제':'공지 고정'}</button><button id="post-hide" class="nodo-button">글 숨기기</button>`:''}</div></article><section class="nodo-card" style="margin-top:20px"><h2>댓글</h2><div id="board-replies"></div><button id="reply-more" class="nodo-button" hidden>댓글 더 보기</button>${post.is_deleted?'<p class="nodo-muted">삭제된 글에는 댓글을 작성할 수 없습니다.</p>':auth?.session?'<form id="reply-form" class="nodo-stack" style="margin-top:20px"><label class="nodo-field">댓글 작성<textarea id="reply-text" required maxlength="1000" rows="3"></textarea></label><button class="nodo-button primary" id="reply-send" style="justify-self:start">댓글 등록</button></form>':'<button id="reply-login" class="nodo-button" style="margin-top:16px">로그인하고 댓글 쓰기</button>'}</section>`;
    if($('post-edit'))$('post-edit').onclick=()=>editor(post);
    if($('post-delete'))$('post-delete').onclick=action(async()=>{if(!confirm('이 글을 삭제할까요?'))return;await api.request('/api/comments/'+id,{method:'DELETE'});navigate();});
    if($('post-pin'))$('post-pin').onclick=action(async()=>{await api.request('/api/board/posts/'+id+'/pin',{method:'PUT',body:JSON.stringify({pinned:!post.pinned})});render();});
    if($('post-hide'))$('post-hide').onclick=action(async()=>{if(!confirm('이 글과 댓글을 게시판에서 숨길까요?'))return;await api.request('/api/admin/comments/'+id+'/moderation',{method:'PUT',body:JSON.stringify({hidden:true,category:'board',detail:'게시판 운영 관리'})});navigate();});
    if($('reply-login'))$('reply-login').onclick=()=>api.login();
    if($('reply-form'))$('reply-form').onsubmit=async e=>{e.preventDefault();$('reply-send').disabled=true;try{await api.create('/api/comments',{page_id:'community',parent_id:Number(id),content:$('reply-text').value});render();}catch(error){message(error);$('reply-send').disabled=false;}};
    let replyOffset=0;
    async function replies(){try{const res=await api.request(`/api/comments/${id}/replies?offset=${replyOffset}&limit=20`);if(token!==generation)return;for(const reply of res.data){const el=document.createElement('div');el.dataset.commentId=reply.id;el.style.cssText='padding:16px 0;border-bottom:1px solid var(--border)';el.innerHTML=`<p class="nodo-muted">${esc(reply.profiles.nickname)} · ${date(reply.created_at)}</p><p style="white-space:pre-wrap;overflow-wrap:anywhere">${esc(reply.content)}</p>`;if(auth?.session?.user.id===reply.user_id&&!reply.is_deleted){const edit=document.createElement('button');edit.className='nodo-button';edit.textContent='수정';edit.onclick=()=>{const input=document.createElement('textarea');input.className='nodo-reply-edit';input.maxLength=1000;input.value=reply.content;input.style.cssText='width:100%;padding:10px;background:var(--bg);color:var(--text);border:1px solid var(--border)';const save=document.createElement('button');save.className='nodo-button';save.textContent='저장';save.onclick=action(async()=>{await api.request('/api/comments/'+reply.id,{method:'PATCH',body:JSON.stringify({content:input.value})});render();});el.replaceChildren(input,save);};const del=document.createElement('button');del.className='nodo-button';del.textContent='삭제';del.onclick=action(async()=>{if(confirm('댓글을 삭제할까요?')){await api.request('/api/comments/'+reply.id,{method:'DELETE'});render();}});el.append(edit,del);}$('board-replies').append(el);}replyOffset+=res.data.length;$('reply-more').hidden=replyOffset>=res.count;if(!replyOffset)$('board-replies').textContent='아직 댓글이 없습니다.';}catch(error){message(error);$('reply-more').hidden=false;$('reply-more').textContent='댓글 다시 불러오기';}}
    $('reply-more').onclick=action(replies);await replies();
    const focus=new URLSearchParams(location.search).get('comment');if(focus&&/^\d+$/.test(focus)){let target=document.querySelector('[data-comment-id="'+focus+'"]');if(Number(focus)===Number(id))target=$('board-content').querySelector('article');if(!target){try{const selected=await api.request('/api/comments/focus?'+new URLSearchParams({id:focus,page_id:'community'}));const item=selected.data.find(c=>String(c.id)===focus);if(item&&Number(item.parent_id)===Number(id)){target=document.createElement('div');target.textContent=item.content;$('board-replies').prepend(target);}}catch{message(Error('원문 댓글을 찾을 수 없거나 공개되지 않은 상태입니다.'));}}if(target){target.classList.add('member-highlight');target.scrollIntoView({block:'center'});}}

  }
  async function render(){const token=++generation;message();const p=new URLSearchParams(location.search);query=p.get('q')||'';offset=Math.max(0,Math.floor(Number(p.get('offset'))||0));hidden=p.get('hidden')==='1';$('board-content').innerHTML='<div class="nodo-status">게시판을 불러오는 중…</div>';try{if(p.has('post')){if(!/^\d+$/.test(p.get('post')))throw Error('올바르지 않은 글 주소입니다.');await detail(p.get('post'),token);}else await list(token);}catch(error){if(token!==generation)return;message(error);$('board-content').innerHTML='<button class="nodo-button" id="board-retry">다시 시도</button> <a class="nodo-button" href="/board/">글 목록</a>';$('board-retry').onclick=render;}}
  $('board-write').onclick=()=>editor();window.addEventListener('popstate',render);
  api.getState().then(state=>auth=state).catch(error=>message(error)).finally(render);
})();
