(() => {
 'use strict';
 const $=id=>document.getElementById(id),fields=()=>[...document.querySelectorAll('input[id],select[id]')].filter(e=>!e.id.startsWith('member-'));
 let member,context=null,last=null,latestRows=[],saving=Promise.resolve(),restoring=false,baseline=0,owner=null,retrySave=null,pendingKind=null;
 const resultIds={loan:'loan-result',prepay:'prepay-result',j2w:'c1-result',w2j:'c2-result',rentcompare:'c3-result',opportunity:'opp-result',savings:'savings-result',deposit:'deposit-result'};
 const funcs={loan:'calcLoan',prepay:'calcPrepay',j2w:'calcJ2W',w2j:'calcW2J',rentcompare:'calcCompare',opportunity:'calcOpportunity',savings:'calcSavings',deposit:'calcDeposit'};
 const input=()=>Object.fromEntries(fields().map(e=>[e.id,e.type==='checkbox'?String(e.checked):e.value]));
 function restore(inputs){for(const [id,value] of Object.entries(inputs||{})){const e=$(id);if(!e||!fields().includes(e))continue;if(e.type==='checkbox')e.checked=value==='true';else e.value=value;}if(window.syncCommon)syncCommon();for(const [id,value] of Object.entries(inputs||{})){const e=$(id);if(!e||!fields().includes(e))continue;if(e.type!=='checkbox')e.value=value;if(e.type==='text'&&window.updateHint)updateHint(e,Number(String(e.value).replaceAll(',',''))||0);}}
 function result(kind){const clone=$(kind==='loan'?'loan-stats':resultIds[kind])?.cloneNode(true);if(!clone)return '';clone.querySelectorAll('canvas,table,button,input,select,script').forEach(e=>e.remove());return (clone.textContent||'').replace(/[ \t]+/g,' ').trim().slice(0,6500);}
 function fieldName(e){return (document.querySelector(`label[for="${e.id}"]`)?.textContent||e.closest('label')?.textContent||e.parentElement.querySelector('label')?.textContent||e.id).trim().replace(/\s+/g,' ');}
 function labels(){return fields().map(e=>{const name=document.querySelector(`label[for="${e.id}"]`)?.textContent||e.closest('label')?.textContent||e.parentElement.querySelector('label')?.textContent||e.id;return name.trim().replace(/\s+/g,' ')+' : '+(e.type==='checkbox'?(e.checked?'적용':'미적용'):e.tagName==='SELECT'?e.selectedOptions[0]?.textContent:e.value);}).join('\n');}
 function status(s){$('member-save-status').textContent=s;}
 async function persist(snapshot,named=false){const state=await NodoAPI.getState(true);if(!state.session||state.session.user.id!==owner){status('로그인 계정이 변경되었습니다. 다시 계산해 주세요.');return;}const kind=snapshot.kind,id=named?(snapshot.saveId??=crypto.randomUUID()):`recent-${owner}-${kind}`,old=named?null:latestRows.find(x=>x.id===id);const name=named?(snapshot.saveName??=$('member-save-name').value.trim()):member.kindNames[kind]+' 최근 결과';if(!name){status('저장할 이름을 입력해 주세요.');return;}retrySave=()=>persist(snapshot,named);status('저장 중…');const data={kind,slot:named?null:'recent',name,payload:snapshot.payload,version:old?.version||0};try{const response=await member.api('/api/me/calculations/'+id,'PUT',data);if(old)old.version=response.version;else latestRows.push({id,version:response.version});status('저장 완료 · '+new Date().toLocaleTimeString('ko-KR'));$('member-save-retry').hidden=true;retrySave=null;}catch(e){status('저장 실패 · '+e.message);$('member-save-retry').hidden=false;if(e.status===409){latestRows=(await member.api('/api/me/calculations')).data;status('다른 기기의 결과를 확인했습니다. 재시도를 누르면 현재 결과를 새로 저장합니다.');}}}
 function completed(kind){if(!member){pendingKind=kind;return;}if(restoring)return;const inputs=input();if(fields().some(e=>e.type==='number'&&!e.checkValidity()))return;last={kind,payload:{schema:1,formula:1,inputs,inputNames:Object.fromEntries(fields().map(e=>[e.id,fieldName(e)])),inputLabels:labels(),result:result(kind),calculatedAt:Date.now(),context:context?{...context,adjustedPrice:window.raw?raw('g_price'):null}:null}};if(!last.payload.result)return;$('member-save-named').disabled=false;if(owner){const snapshot=structuredClone(last);saving=saving.then(()=>persist(snapshot)).catch(e=>status(e.message));}else status('로그인하면 최근 계산 결과가 자동 저장됩니다.');}
 function priceChange(mode){const price=$('g_price');if(!context||!price)return;let value;if(mode==='rate'){const rate=Number($('member-price-rate').value);value=Math.round(baseline*(1+rate/100));}else value=Number($('member-price-amount').value);if(!Number.isFinite(value)||value<=0){status('매매금액은 0보다 커야 합니다.');return;}value=Math.round(value);context.adjustedPrice=value;try{sessionStorage.setItem('nodo-calculator-active',JSON.stringify(context));}catch{}$('member-price-amount').value=value;$('member-price-rate').value=((value/baseline-1)*100).toFixed(2);price.value=value.toLocaleString('ko-KR');if(window.updateHint)updateHint(price,value);if(window.syncCommon)syncCommon();$('member-price-info').textContent=(value/10000).toLocaleString('ko-KR',{maximumFractionDigits:4})+'억 원 · 기준 대비 '+((value/baseline-1)*100).toFixed(2)+'%';if(last&&['loan','opportunity'].includes(last.kind))window[funcs[last.kind]]();}
 function showContext(){if(!context||!$('g_price'))return;baseline=context.price;let box=$('member-price-context');if(!box){box=document.createElement('section');box.id='member-price-context';box.className='nodo-card';$('member-calculator').after(box);}box.replaceChildren();const heading=document.createElement('h2');heading.textContent=context.name+' · '+context.area+'㎡';const desc=document.createElement('p');desc.textContent='기준 거래 '+(baseline/10000)+'억 원 · '+String(context.date).replace(/^(\d{4})(\d{2})(\d{2})$/,'$1-$2-$3')+' · '+(context.floor??'미확인')+'층';box.append(heading,desc);const buttons=document.createElement('div');buttons.className='nodo-actions';for(const n of [-10,-5,0,5,10]){const b=document.createElement('button');b.className='nodo-button';b.textContent=n===0?'기준가':(n>0?'+':'')+n+'%';b.onclick=()=>{$('member-price-rate').value=n;priceChange('rate');};buttons.append(b);}box.append(buttons);box.insertAdjacentHTML('beforeend','<div class="nodo-actions"><label>매수가 조정률 (%) <input id="member-price-rate" type="number" step="0.1" value="0"></label><label>매매금액 (만원) <input id="member-price-amount" type="number" min="1" step="1"></label></div><p id="member-price-info" role="status"></p><p class="nodo-muted">이번 매수가 조정입니다. 향후 연간 집값 상승률은 아래에서 별도로 설정합니다.</p>');$('member-price-amount').value=context.adjustedPrice||baseline;$('member-price-amount').onchange=()=>priceChange('amount');$('member-price-rate').onchange=()=>priceChange('rate');priceChange('amount');$('g_price').addEventListener('change',()=>{$('member-price-amount').value=window.raw?raw('g_price'):baseline;priceChange('amount');});}
 async function init(){if($('member-calculator')||!window.NodoMember)return;member=NodoMember;const box=document.createElement('section');box.id='member-calculator';box.className='nodo-card member-main';box.innerHTML='<h2>계산 결과 보관</h2><p id="member-save-guide"></p><div class="nodo-actions"><input id="member-save-name" maxlength="80" placeholder="예: 5% 낮춘 매수안" aria-label="계산 이름"><button class="nodo-button" id="member-save-named" disabled>이름 붙여 저장</button><a href="/library/?tab=calculations">저장한 계산 보기</a><button id="member-save-login" class="nodo-button">Google로 로그인</button></div><p id="member-save-status" role="status"></p><button id="member-save-retry" class="nodo-button" hidden>저장 재시도</button>';const title=document.querySelector('h1');const heading=title?.parentElement?.parentElement;if(heading&&heading!==document.body)heading.after(box);else(document.querySelector('main')||document.body).append(box);owner=member.getState()?.session?.user.id||null;$('member-save-login').hidden=!!owner;$('member-save-guide').textContent=owner?'계산을 완료하면 종류별 최근 결과가 자동 저장됩니다. 비교할 조건은 이름을 붙여 별도로 보관하세요.':'로그인하면 최근 계산 결과가 자동 저장되고, 다른 기기에서도 이어서 볼 수 있어요.';
  $('member-save-login').onclick=()=>{try{sessionStorage.setItem('nodo-login-calculator',JSON.stringify({path:location.pathname,inputs:input(),context,last}));}catch{}NodoAPI.login();};$('member-save-named').onclick=()=>{if(!owner){$('member-save-login').click();return;}const snap=structuredClone(last);$('member-save-named').disabled=true;saving=saving.then(()=>persist(snap,true)).finally(()=>$('member-save-named').disabled=false);};$('member-save-retry').onclick=()=>{if(retrySave)saving=saving.then(retrySave);};if(owner)latestRows=(await member.api('/api/me/calculations')).data;
  const params=new URLSearchParams(location.search);restoring=true;let restored=null;
  try{if(!params.has('restore')&&!params.has('fromApartment')&&$('g_price')){context=JSON.parse(sessionStorage.getItem('nodo-calculator-active')||'null');if(!context||!Number.isFinite(context.price)||context.price<=0)context=null;}if(params.has('restore')){restored=JSON.parse(sessionStorage.getItem('nodo-calculator-restore')||'null');sessionStorage.removeItem('nodo-calculator-restore');if(restored){restore(restored.payload.inputs);context=restored.payload.context;if(!context)sessionStorage.removeItem('nodo-calculator-active');status('저장 당시 조건을 불러왔습니다. 계산 버튼을 누르면 현재 계산식으로 다시 계산합니다.');}}
   else if(params.has('fromApartment')){context=JSON.parse(sessionStorage.getItem('nodo-calculator-context')||'null');sessionStorage.removeItem('nodo-calculator-context');if(context&&Number.isFinite(context.price)&&context.price>0){$('g_price').value=context.price.toLocaleString('ko-KR');$('l_base').value='buy';if(window.syncCommon)syncCommon();}else context=null;}
   const pending=JSON.parse(sessionStorage.getItem('nodo-login-calculator')||'null');if(pending?.path===location.pathname&&owner){sessionStorage.removeItem('nodo-login-calculator');restore(pending.inputs);context=pending.context;last=pending.last;if(last){$('member-save-named').disabled=false;saving=saving.then(()=>persist(last));}}
  }catch{status('이전 입력을 복원하지 못했습니다. 다시 선택해 주세요.');}showContext();if(restored&&['savings','deposit'].includes(restored.kind)&&window.switchMain)switchMain(restored.kind);if(restored?.kind==='prepay'&&window.calcLoan)calcLoan();if(restored&&['j2w','w2j','rentcompare'].includes(restored.kind)&&window.switchConvTab)switchConvTab(restored.kind==='rentcompare'?'compare':restored.kind);if(restored){const target=$(resultIds[restored.kind])?.closest('[id^=sec-]');target?.scrollIntoView({block:'start'});}restoring=false;if(pendingKind){const kind=pendingKind;pendingKind=null;completed(kind);}if(params.has('fromApartment')||params.has('restore')){params.delete('fromApartment');params.delete('restore');history.replaceState(null,'',location.pathname+(params.size?'?'+params:''));}NodoAPI.onChange(()=>{owner=null,retrySave=null,pendingKind=null;last=null;status('로그인 상태가 변경되었습니다. 새로고침 후 다시 계산해 주세요.');});
 }
 document.addEventListener('nodo:calculated',e=>completed(e.detail));document.addEventListener('nodo:member-ready',()=>init().catch(e=>NodoMember.notice(e.message)));if(window.NodoMember)init().catch(e=>NodoMember.notice(e.message));
})();
