/* Private member library and anonymous apartment analytics. */
(() => {
 'use strict';
 const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),money=n=>n==null?'자료 없음':(n/10000).toLocaleString('ko-KR',{maximumFractionDigits:4})+'억 원',date=n=>String(n||'').replace(/^(\d{4})(\d{2})(\d{2})$/,'$1-$2-$3');
 const fetchJSON=async path=>{const r=await fetch(path,{cache:'no-store'});if(!r.ok)throw Error('자료를 불러오지 못했습니다. 다시 시도해 주세요.');return r.json();};
 let catalogPromise,favorites=null,state=null,active=null,renderVersion=0;
 const catalog=()=>catalogPromise??=fetchJSON('/data/apartments/index.json').catch(e=>{catalogPromise=null;throw e;});
 const shards=new Map();
 async function summary(id){const c=await catalog(),ref=c.lookup[id]||c.legacy[id];if(!ref)return null;const canonical=c.lookup[ref[0]];if(!canonical)return null;const shard=canonical[1];if(!shards.has(shard))shards.set(shard,fetchJSON('/data/apartments/summary/'+shard+'.json').catch(e=>{shards.delete(shard);throw e;}));return (await shards.get(shard))[canonical[0]];}
 function notice(message){let box=$('member-toast');if(!box){box=document.createElement('div');box.id='member-toast';box.className='member-toast';box.setAttribute('role','status');document.body.append(box);}box.textContent=message;box.hidden=false;clearTimeout(box.timer);box.timer=setTimeout(()=>box.hidden=true,5500);}
 const api=(path,method='GET',data)=>NodoAPI.request(path,{method,...(data?{body:JSON.stringify(data)}:{})});
 async function loadFavorites(){if(!state?.session)return [];if(!favorites)favorites=(await api('/api/me/favorites')).data.map(x=>({...x,areas:JSON.parse(x.areas)}));return favorites;}
 function source(){const p=new URLSearchParams(location.search);if(['search','map','favorites','ranking','internal'].includes(p.get('from')))return p.get('from');try{const ref=new URL(document.referrer);if(ref.origin!==location.origin)return 'direct';return ref.pathname.startsWith('/map')?'map':ref.pathname.startsWith('/library')?'favorites':ref.pathname.startsWith('/ranking')?'ranking':ref.pathname==='/'?'search':'internal';}catch{return 'direct';}}
 const sent=new Set();let eventQueue=Promise.resolve();
 function event(kind,a=active?.apartment,area=active?.area){if(!a)return;const key=[a.id,area?.area||'none',kind].join('|');if(sent.has(key))return;sent.add(key);eventQueue=eventQueue.then(()=>fetch('/api/apartments/events',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({apartmentId:a.id,area:String(area?.area||'none'),kind,source:source()}),keepalive:true})).catch(()=>{});}
 async function toggle(a,area,button){if(!state?.session){NodoAPI.login();return;}button.disabled=true;try{const rows=await loadFavorites(),old=rows.find(x=>x.apartment_id===a.id);if(!old&&!area){const full=await summary(a.id);area=[...(full?.areas||[])].sort((x,y)=>(y.latest?.date||0)-(x.latest?.date||0)||x.area-y.area)[0];}await api('/api/me/favorites/'+encodeURIComponent(a.id),old?'DELETE':'PUT',{version:old?.version||0,areas:area?[String(area.area)]:[]});favorites=null;if(!old)event('heart',a,area);notice(old?'관심 단지를 해제했습니다.':'관심 단지에 저장했습니다.');await refreshHearts();if(document.querySelector('[data-member-page="library"]'))await renderLibrary();}catch(e){notice(e.message);favorites=null;}finally{button.disabled=false;}}
 async function heartButton(a,area){const b=document.createElement('button');b.className='nodo-button member-heart';b.dataset.heart=a.id;b.setAttribute('aria-label',a.name+' 관심 등록');b.onclick=e=>{e.preventDefault();e.stopPropagation();toggle(a,area,b);};b.textContent='♡';return b;}
 async function refreshHearts(){const buttons=[...document.querySelectorAll('[data-heart]')];if(!buttons.length)return;const ids=[...new Set(buttons.map(b=>b.dataset.heart))],mine=await loadFavorites();const counts={};for(let i=0;i<ids.length;i+=100)Object.assign(counts,(await api('/api/apartments/hearts?ids='+encodeURIComponent(ids.slice(i,i+100).join(',')))).data);for(const b of buttons){const liked=mine.some(x=>x.apartment_id===b.dataset.heart);b.textContent=(liked?'♥ ':'♡ ')+(counts[b.dataset.heart]||0);b.setAttribute('aria-pressed',String(liked));}}
 function toCalculator(a,area,trade){if(!trade||trade.flags&6)return;const context={id:a.id,name:a.name,area:area.area,price:trade.price,date:trade.date,floor:trade.floor,updated:a.updated};try{sessionStorage.setItem('nodo-calculator-context',JSON.stringify(context));}catch{notice('브라우저 저장소를 사용할 수 없습니다.');return;}event('calculator',a,area);location.assign('/calc/?fromApartment=1');}
 function calcButton(a,area,trade){const b=document.createElement('button');b.className='nodo-button';b.textContent='이 가격으로 계산';b.onclick=()=>toCalculator(a,area,trade);b.disabled=!trade||!!(trade.flags&6);return b;}
 async function detail(){active=window.NodoCurrentApartment;if(!active||!$('apartment-content')||$('apartment-content').hidden)return;let box=$('member-detail-actions');if(!box){box=document.createElement('div');box.id='member-detail-actions';box.className='nodo-actions';$('apartment-facts').after(box);}const a=active.apartment,area=active.area;box.replaceChildren(await heartButton(a,area),calcButton(a,area,area?.latest));refreshHearts().catch(e=>notice(e.message));event('view');if(new URLSearchParams(location.search).get('tab')==='trades')event('trades');}
 const href=(a,area,from='favorites')=>'/apartment/?'+new URLSearchParams({id:a.id,...(area?{area:area.area}:{}),from});
 async function card(a,selected,rank,compact=false){const card=document.createElement('article');card.className='nodo-card member-card';const title=document.createElement('div');title.className='nodo-actions';title.innerHTML=`<h2><a href="${esc(href(a,selected[0],rank?'ranking':'favorites'))}">${rank?rank+'위 · ':''}${esc(a.name)}</a></h2>`;title.append(await heartButton(a,selected[0]));card.append(title);const desc=document.createElement('p');desc.className='nodo-muted';desc.textContent=a.address+' · 자료 기준 '+a.updated;card.append(desc);if(compact){const p=document.createElement('p');p.textContent=selected[0]?selected[0].area+'㎡ · '+money(selected[0].latest?.price)+' · '+date(selected[0].latest?.date):'매매 거래 자료 없음';card.append(p);return card;}
  for(const area of selected){const row=document.createElement('section');row.className='member-area';const t=area.latest;row.innerHTML=`<h3>${esc(area.area)}㎡ · ${money(t?.price)}</h3><p>${t?date(t.date)+' · '+esc(t.floor??'미확인')+'층'+(t.flags&1?' · 직거래':''):'매매 거래 자료 없음'}</p><p class="nodo-muted">최근 평균 ${money(area.recent?.value)}${area.recent?' · '+area.recent.from+'–'+area.recent.to+' · '+area.recent.count+'건':''}</p>`;row.append(calcButton(a,area,t));const details=document.createElement('details');details.innerHTML='<summary>최근 거래 5건 펼치기</summary>';for(const tx of area.lastFive||[]){const line=document.createElement('div');line.className='nodo-actions';line.append(document.createTextNode(`${date(tx.date)} · ${money(tx.price)} · ${tx.floor??'미확인'}층 `),calcButton(a,area,tx));details.append(line);}row.append(details);card.append(row);}
  if(!selected.length){const p=document.createElement('p');p.textContent='매매 거래 자료 없음';card.append(p);}return card;
 }
 function pageError(box,e,retry){box.innerHTML='<p>'+esc(e.message)+'</p>';const b=document.createElement('button');b.className='nodo-button';b.textContent='다시 시도';b.onclick=retry;box.append(b);}
 async function renderLibrary(){const box=$('member-content'),token=++renderVersion;box.innerHTML='<p>불러오는 중…</p>';if(!state?.session){box.innerHTML='<p>로그인하면 관심 아파트와 계산 결과를 여러 기기에서 이어서 볼 수 있습니다.</p><button class="nodo-button" id="library-login">Google로 로그인</button>';$('library-login').onclick=()=>NodoAPI.login();return;}
  try{const tab=new URLSearchParams(location.search).get('tab');box.innerHTML='<nav class="nodo-actions"><a class="nodo-button" href="/library/">관심 아파트</a><a class="nodo-button" href="/library/?tab=calculations">저장한 계산</a><a class="nodo-button" href="/ranking/">하트 랭킹</a></nav><div id="library-items" class="nodo-stack"></div>';const list=$('library-items');if(tab==='calculations'){await calculations(list);return;}
   const rows=await loadFavorites(),data=await Promise.all(rows.map(async f=>({f,a:await summary(f.apartment_id)})));if(token!==renderVersion)return;
   const select=document.createElement('select');select.className='nodo-button';select.setAttribute('aria-label','관심 목록 정렬');select.innerHTML='<option value="saved">관심 등록순</option><option value="date">최신 거래일순</option><option value="price">가격 높은순</option>';list.before(select);
   const draw=async()=>{list.replaceChildren();const sorted=[...data];const metric=x=>Math.max(0,...(x.a?.areas||[]).filter(v=>x.f.areas.includes(String(v.area))).map(v=>v.latest?.[select.value==='price'?'price':'date']||0));if(select.value!=='saved')sorted.sort((a,b)=>metric(b)-metric(a));if(!sorted.length)list.innerHTML='<p>아직 관심 단지가 없습니다. 단지의 하트를 눌러 추가해 보세요.</p>';
    for(const {f,a} of sorted){if(!a){const c=document.createElement('article');c.className='nodo-card';c.textContent=f.name+' · 현재 단지 연결을 확인할 수 없습니다.';const b=document.createElement('button');b.textContent='관심 해제';b.onclick=()=>toggle({id:f.apartment_id,name:f.name},null,b);c.append(b);list.append(c);continue;}
     const selected=a.areas.filter(v=>f.areas.includes(String(v.area))),c=await card(a,selected);if(!selected.length&&a.areas.length)c.querySelector('p:last-child').textContent='아래에서 관심 평형을 선택해 주세요.';const edit=document.createElement('details');edit.innerHTML='<summary>관심 평형 변경</summary>'+a.areas.map(v=>`<label class="member-check"><input type="checkbox" value="${esc(v.area)}" ${f.areas.includes(String(v.area))?'checked':''}> ${esc(v.area)}㎡</label>`).join('');const save=document.createElement('button');save.className='nodo-button';save.textContent='평형 저장';save.onclick=async()=>{save.disabled=true;try{await api('/api/me/favorites/'+encodeURIComponent(a.id),'PUT',{version:f.version,areas:[...edit.querySelectorAll('input:checked')].map(i=>i.value)});favorites=null;await renderLibrary();}catch(e){notice(e.message);favorites=null;}finally{save.disabled=false;}};edit.append(save);c.append(edit);list.append(c);
    }refreshHearts().catch(e=>notice(e.message));};select.onchange=draw;await draw();
  }catch(e){pageError(box,e,renderLibrary);}
 }
 async function ranking(box,top=false){try{const p=new URLSearchParams(location.search),region=top?'':p.get('region')||'',district=top?'':p.get('district')||'',offset=top?0:Number(p.get('offset'))||0;const result=await api('/api/apartments/ranking?'+new URLSearchParams({region,district,offset}));box.replaceChildren();if(!top){const form=document.createElement('form');form.className='nodo-actions';form.innerHTML='<label>지역 <select name="region">'+['','서울','경기','인천'].map(v=>`<option value="${v}" ${v===region?'selected':''}>${v||'전체'}</option>`).join('')+'</select></label><label>시군구 <select name="district"><option value="">전체</option>'+result.districts.map(v=>`<option ${v===district?'selected':''}>${esc(v)}</option>`).join('')+'</select></label><button class="nodo-button">보기</button>';form.querySelector('[name=region]').onchange=()=>{form.querySelector('[name=district]').value='';form.requestSubmit();};box.append(form);}
   const rows=top?result.data.slice(0,10):result.data;if(!rows.length)box.insertAdjacentHTML('beforeend','<p>아직 관심 등록된 단지가 없습니다.</p>');for(const row of rows){const a=await summary(row.apartment_id);if(!a)continue;const area=[...a.areas].filter(x=>x.latest).sort((x,y)=>y.latest.date-x.latest.date||x.area-y.area)[0];box.append(await card(a,area?[area]:[],row.rank,top));}if(!top){const nav=document.createElement('nav');nav.className='nodo-actions';for(const [label,n,visible] of [['이전',offset-50,offset>0],['다음',offset+50,result.data.length===50]])if(visible)nav.insertAdjacentHTML('beforeend',`<a href="?${esc(new URLSearchParams({region,district,offset:n}))}">${label}</a>`);box.append(nav);}refreshHearts().catch(()=>{});
  }catch(e){pageError(box,e,()=>ranking(box,top));}}
 const kindNames={loan:'대출',prepay:'중도상환',j2w:'전세 → 월세',w2j:'월세 → 전세',rentcompare:'전세대출·월세 비교',opportunity:'매매·전세·월세 비교',savings:'적금',deposit:'예금'};
 async function calculations(box){const rows=(await api('/api/me/calculations')).data;if(!rows.length){box.innerHTML='<p>저장한 계산이 없습니다. 계산기에서 계산하면 최근 결과가 자동 저장됩니다.</p>';return;}const compare=document.createElement('button');compare.className='nodo-button';compare.textContent='선택한 계산 비교 (최대 3개)';const selection=new Set();box.append(compare);const comparison=document.createElement('div');box.append(comparison);
  compare.onclick=()=>{const chosen=rows.filter(x=>selection.has(x.id));if(chosen.length<2||chosen.length>3||new Set(chosen.map(x=>x.kind)).size!==1){notice('같은 계산 종류를 2~3개 선택해 주세요.');return;}comparison.className='member-comparison';comparison.replaceChildren();const snapshots=chosen.map(x=>JSON.parse(x.payload)),keys=[...new Set(snapshots.flatMap(p=>Object.keys(p.inputs)))].filter(k=>new Set(snapshots.map(p=>p.inputs[k])).size>1);for(const row of chosen){const p=JSON.parse(row.payload),c=document.createElement('article');c.className='nodo-card';c.innerHTML=`<h3>${esc(row.name)}</h3><p>${esc(new Date(p.calculatedAt).toLocaleString('ko-KR'))}</p><h4>달라진 조건</h4><pre>${keys.length?esc(keys.map(k=>(p.inputNames?.[k]||k)+' : '+(p.inputs[k]??'미입력')).join('\n')):'입력 조건이 같습니다.'}</pre><details><summary>전체 조건</summary><pre>${esc(p.inputLabels||JSON.stringify(p.inputs,null,2))}</pre></details><h4>저장 당시 결과</h4><pre>${esc(p.result)}</pre>`;comparison.append(c);}};
  for(const row of rows){const p=JSON.parse(row.payload),c=document.createElement('article');c.className='nodo-card';c.innerHTML=`<label><input type="checkbox"> 비교 선택</label><h3>${esc(row.name)} ${row.slot?'· 최근 결과':''}</h3><p>${esc(kindNames[row.kind])} · ${esc(new Date(p.calculatedAt).toLocaleString('ko-KR'))}</p>${p.context?'<p>'+esc(p.context.name)+' · '+esc(p.context.area)+'㎡ · 기준 '+money(p.context.price)+'</p>':''}<details><summary>저장한 조건과 결과</summary><pre>${esc(p.inputLabels||JSON.stringify(p.inputs,null,2))}</pre><pre>${esc(p.result)}</pre></details>`;c.querySelector('input').onchange=e=>e.target.checked?selection.add(row.id):selection.delete(row.id);
   const actions=document.createElement('div');actions.className='nodo-actions';const open=document.createElement('button');open.className='nodo-button';open.textContent='입력 복원·다시 계산';open.onclick=()=>{try{sessionStorage.setItem('nodo-calculator-restore',JSON.stringify({kind:row.kind,payload:p}));location.assign(['savings','deposit'].includes(row.kind)?'/calc/savings.html?restore=1':'/calc/?restore=1');}catch{notice('브라우저 저장소를 사용할 수 없습니다.');}};actions.append(open);
   const name=document.createElement('input');name.value=row.name;name.maxLength=80;name.setAttribute('aria-label','계산 이름');const rename=document.createElement('button');rename.className='nodo-button';rename.textContent='이름 변경';rename.onclick=async()=>{try{await api('/api/me/calculations/'+row.id,'PUT',{...row,payload:p,name:name.value,version:row.version});await renderLibrary();}catch(e){notice(e.message);}};const del=document.createElement('button');del.className='nodo-button';del.textContent='삭제';del.onclick=async()=>{if(!confirm('이 계산을 삭제할까요?'))return;try{await api('/api/me/calculations/'+row.id,'DELETE',{version:row.version});await renderLibrary();}catch(e){notice(e.message);}};actions.append(name,rename,del);c.append(actions);box.append(c);
  }
 }
 async function activity(){const main=$('main-content');if(!main||$('member-activity'))return;const section=document.createElement('section');section.id='member-activity';section.className='card';section.innerHTML='<h2>내 활동</h2><div class="nodo-actions"><button data-activity="posts">내 글</button><button data-activity="comments">내 댓글</button><button data-activity="replies">받은 답글</button><a href="/library/">내 보관함</a></div><div id="activity-list"></div>';main.prepend(section);let kind='posts',offset=0,sequence=0;
  async function draw(){const seq=++sequence,box=$('activity-list');box.textContent='불러오는 중…';try{const rows=(await api('/api/me/activity?'+new URLSearchParams({type:kind,offset}))).data;if(seq!==sequence)return;box.replaceChildren();const cat=await catalog();for(const row of rows){let url='',label=row.page_id;if(row.page_id==='community'){url='/board/?post='+(row.parent_id||row.id);label='공용 게시판';}else if(row.page_id.startsWith('apt_')){const ref=cat.legacy[row.page_id.slice(4)];if(ref){url='/apartment/?'+new URLSearchParams({id:ref[0],area:ref[1],tab:'comments',commentSource:row.page_id});const a=await summary(ref[0]);label=(a?.name||'아파트')+' · '+ref[1]+'㎡';}}else if(/^company_\d{6}$/.test(row.page_id)){url='/div/?company='+row.page_id.slice(8);label='기업 '+row.page_id.slice(8);}else if(row.page_id==='div'){url='/div/';label='배당·소각';}const c=document.createElement('article');c.className='member-area';c.innerHTML=`<p>${esc(label)} · ${esc(row.created_at)}</p><p>${esc(row.content.slice(0,250))}</p>${url?`<a href="${esc(url+(url.includes('?')?'&':'?')+'comment='+row.id)}">원문에서 보기</a>`:'<p>원문 위치를 확인할 수 없습니다.</p>'}`;box.append(c);}if(!rows.length)box.textContent='아직 표시할 활동이 없습니다.';for(const [label,n,visible] of [['이전',offset-30,offset>0],['다음',offset+30,rows.length===30]])if(visible){const b=document.createElement('button');b.textContent=label;b.onclick=()=>{offset=n;draw();};box.append(b);}}catch(e){pageError(box,e,draw);}}
  section.querySelectorAll('[data-activity]').forEach(b=>b.onclick=()=>{kind=b.dataset.activity;offset=0;draw();});draw();
 }
 async function admin(){const main=$('screen-app')||document.querySelector('main')||document.querySelector('.container')||document.body;const section=document.createElement('section');section.className='nodo-card';section.innerHTML='<h2>단지 조회 통계</h2><p>한국 시간 기준 · 방문 세션은 실제 사람 수와 다릅니다. 후속 행동은 같은 방문의 집계입니다.</p><select aria-label="통계 기간"><option value="1">오늘</option><option value="7" selected>최근 7일</option><option value="30">최근 30일</option></select><div class="member-analytics"></div>';main.prepend(section);const select=section.querySelector('select'),box=section.querySelector('div');async function draw(){try{const result=await api('/api/admin/apartment-analytics?days='+select.value);box.innerHTML='<p>'+result.sources.map(s=>esc(({search:'검색',map:'지도',favorites:'관심 목록',ranking:'랭킹',internal:'기타 내부',direct:'직접·외부'})[s.source]||s.source)+': '+s.views+'회').join(' · ')+'</p>';const table=document.createElement('table');table.className='nodo-table';table.innerHTML='<thead><tr><th>단지</th><th>조회</th><th>방문 세션</th><th>관심 전환</th><th>실거래</th><th>계산 전환</th></tr></thead><tbody></tbody>';for(const row of result.data){const a=await summary(row.apartment_id);table.querySelector('tbody').insertAdjacentHTML('beforeend',`<tr><td>${esc(a?.name||row.apartment_id)}</td><td>${row.views}</td><td>${row.sessions}</td><td>${row.hearts} (${row.sessions?(row.hearts/row.sessions*100).toFixed(1):0}%)</td><td>${row.trades}</td><td>${row.calculators} (${row.sessions?(row.calculators/row.sessions*100).toFixed(1):0}%)</td></tr>`);}box.append(table);}catch(e){pageError(box,e,draw);}}select.onchange=draw;draw();}
 async function init(){if(!window.NodoAPI){await new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='/js/auth-client.js';s.onload=resolve;s.onerror=reject;document.head.append(s);});}state=await NodoAPI.getState();NodoAPI.onChange(s=>{state=s;favorites=null;if(document.querySelector('[data-member-page="library"]'))renderLibrary();refreshHearts().catch(()=>{});});
  window.NodoMember={summary,toCalculator,event,notice,api,getState:()=>state,kindNames};document.dispatchEvent(new Event('nodo:member-ready'));
  const mode=document.querySelector('[data-member-page]')?.dataset.memberPage;if(mode==='library')renderLibrary();if(mode==='ranking')ranking($('member-content'));if(location.pathname.startsWith('/account')&&state?.session)activity();if(location.pathname.startsWith('/admin')&&state?.isAdmin)admin();
  document.addEventListener('nodo:apartment',()=>detail().catch(e=>notice(e.message)));detail().catch(()=>{});
  if(!/^\/(apartment|library|ranking)/.test(location.pathname)){
   let timer,busy=false;const scan=async()=>{if(busy)return;busy=true;try{const links=[...document.querySelectorAll('a[href*="/apartment/?"]')].filter(a=>!a.dataset.memberHeart&& !a.closest('#member-top'));if(!links.length)return;const c=await catalog();for(const link of links){link.dataset.memberHeart='1';const p=new URL(link.href).searchParams,ref=c.lookup[p.get('id')]||c.legacy[p.get('row')];if(!ref)continue;link.after(await heartButton({id:ref[0],name:link.textContent},p.get('area')?{area:p.get('area')}:null));}await refreshHearts();}finally{busy=false;}};
   new MutationObserver(()=>{clearTimeout(timer);timer=setTimeout(()=>scan().catch(()=>{}),300);}).observe(document.body,{childList:true,subtree:true});scan().catch(()=>{});
  }
  document.addEventListener('click',e=>{const b=e.target.closest('[data-calc-trade]');if(b&&window.NodoCurrentApartment){const {apartment,area}=window.NodoCurrentApartment;toCalculator(apartment,area,JSON.parse(b.dataset.calcTrade));}});
  if(location.pathname==='/'||location.pathname==='/index.html'){const section=document.createElement('section');section.className='nodo-card member-main';section.innerHTML='<h2>관심 많은 아파트 TOP 10</h2><a href="/ranking/">전체 랭킹 보기</a><div id="member-top"></div>';(document.querySelector('main')||document.body).append(section);ranking($('member-top'),true);}
 }
 init().catch(e=>{const box=$('member-content');if(box)pageError(box,e,()=>location.reload());});
})();
