/* Isolated local UI preview. All account/post data lives in an ephemeral Miniflare DB. */
import {createServer} from 'node:http';
import {readFileSync,existsSync,statSync,readdirSync} from 'node:fs';
import {resolve,extname,sep} from 'node:path';
import {createHash} from 'node:crypto';
import {build} from 'esbuild';
import {Miniflare} from 'miniflare';
import {publicAsset} from './build-cloudflare-assets.mjs';
const root=resolve(import.meta.dirname,'..'),port=Number(process.env.NODO_PREVIEW_PORT||8793),origin='http://127.0.0.1:'+port;
const bundle=await build({entryPoints:[resolve(root,'cloudflare/src/index.ts')],bundle:true,write:false,format:'esm',platform:'browser',target:'es2022'});
function asset(request){let path=decodeURIComponent(new URL(request.url).pathname).replace(/^\//,'');if(!path||path.endsWith('/'))path+='index.html';if(!existsSync(resolve(root,path))&&!extname(path)){if(existsSync(resolve(root,path,'index.html')))path+='/index.html';else path+='.html';}const filename=resolve(root,path);if(!filename.startsWith(root+sep))return new Response('Not found',{status:404});if(path.split(/[\\/]/).includes('..')||!publicAsset(path)||!existsSync(filename)||!statSync(filename).isFile())return new Response('Not found',{status:404});const types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.svg':'image/svg+xml','.png':'image/png','.bin':'application/octet-stream'};return new Response(readFileSync(filename),{headers:{'Content-Type':types[extname(path)]||'application/octet-stream','Cache-Control':'no-store'}});}
const mf=new Miniflare({modules:true,script:bundle.outputFiles[0].text,compatibilityDate:'2026-08-01',d1Databases:['DB'],bindings:{SITE_ORIGIN:origin,MAINTENANCE:'false',AUTH_ENABLED:'false',RELEASE_SHA:'local-preview'},serviceBindings:{ASSETS:asset}});
const db=await mf.getD1Database('DB');for(const file of readdirSync(resolve(root,'cloudflare/migrations')).filter(f=>f.endsWith('.sql')).sort())for(const sql of readFileSync(resolve(root,'cloudflare/migrations',file),'utf8').split(';').map(s=>s.trim()).filter(Boolean))await db.prepare(sql).run();
const raw='local-preview-admin-session',hash=s=>createHash('sha256').update(s).digest('hex');
await db.batch([db.prepare("INSERT INTO users(id,google_sub,email,role) VALUES('preview','preview','preview@example.invalid','admin')"),db.prepare("INSERT INTO profiles(user_id,nickname) VALUES('preview','미리보기운영자')"),db.prepare('INSERT INTO sessions(token_hash,user_id,expires_at,authenticated_at) VALUES(?,?,?,?)').bind(hash(raw),'preview',Math.floor(Date.now()/1000)+86400,Math.floor(Date.now()/1000))]);
const server=createServer(async(req,res)=>{try{if(req.url==='/__preview/login'){res.writeHead(302,{'Set-Cookie':`__Host-nodo_session=${raw}; Secure; HttpOnly; SameSite=Lax; Path=/`,Location:'/board/'});res.end();return;}const chunks=[];for await(const chunk of req)chunks.push(chunk);const response=await mf.dispatchFetch(origin+req.url,{method:req.method,headers:req.headers,body:['GET','HEAD'].includes(req.method)?undefined:Buffer.concat(chunks)});res.writeHead(response.status,Object.fromEntries(response.headers));res.end(Buffer.from(await response.arrayBuffer()));}catch(error){res.writeHead(500);res.end(String(error));}}).listen(port,'127.0.0.1',()=>console.log('Local preview: '+origin+' (ephemeral database; /__preview/login for test account)'));
process.on('SIGINT',async()=>{server.close();await mf.dispose();process.exit();});
